// koravo-ui/src/components/ui/CopyableText.vue
<template>
  <span class="copyable-text">
    <span class="copyable-value">{{ displayValue || value || '-' }}</span>
    <a-tooltip v-if="hasValue" title="复制">
      <a-button size="small" type="text" @click="copy"><CopyOutlined /></a-button>
    </a-tooltip>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { message } from 'ant-design-vue'
import { CopyOutlined } from '@ant-design/icons-vue'
import { copyText } from '../../utils/format'

const props = defineProps<{
  value?: string | number | null
  displayValue?: string | number | null
}>()

const hasValue = computed(() => props.value !== undefined && props.value !== null && props.value !== '')

async function copy() {
  if (await copyText(props.value)) {
    message.success('已复制')
  }
}
</script>

// koravo-ui/src/components/CopyableText.tsx
import { CopyOutlined } from '@ant-design/icons';
import { Button, Typography, message } from 'antd';
import React from 'react';
import { shortTraceLabel } from '@/utils/display';

export const CopyableText: React.FC<{
  value?: string | number | null;
  displayValue?: string;
}> = ({ value, displayValue }) => {
  if (value === undefined || value === null || value === '') return <>-</>;
  const text = String(value);

  return (
    <Typography.Text>
      {displayValue || shortTraceLabel(text)}
      <Button
        type="text"
        size="small"
        icon={<CopyOutlined />}
        onClick={async () => {
          await navigator.clipboard.writeText(text);
          message.success('已复制');
        }}
      />
    </Typography.Text>
  );
};
